#!/usr/bin/env python3
import sys
from getopt import getopt
import fileinput
import re

def processCommand():
    opts, remainder = getopt(sys.argv[1:],'AB')
    dict_opts = dict(opts)
    print(remainder)
    print(opts)
    return (dict_opts, remainder)

def processText(filename, n, word, d):
    fd = open(filename, 'r')
    file = fd.read()
    # if after
    if (d == '-A'):
        for match in re.findall(rf'{word}((?:\s+\w+){{1,{n}}})', file):
            print(match)
    # if b4
    elif (d == '-B'):
        for match in re.findall(rf'((?:\w+\s+){{1,{n}}}){word}', file):
            print(match)

    fd.close()

processText('exemplo.txt', 3, 'está', '-B')
